    version: '3'
    services:
      nginx:
        image: nginx:latest
        ports:
          - "80:80"
        volumes:
          - ./hosts:/etc/nginx/sites-available
          - ./www:/usr/share/nginx/html
          - ./nginx_logs:/var/log/nginx
